### ISSUE TITLE
github登录需要验证码

### ISSUE THREAD

**Issue by 13068240601** [LeetCode-OpenSource/vscode-leetcode#559]
## 🐛 Bug Report
在新设备使用github登录，github发来了验证码，但是插件没有输入的地方

## To Reproduce

在新设备使用github登录

## Expected behavior

使用github登录时再弹出一个验证码输入框，非必填

## Extension Output

login: (node:7632) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: c:\Users\userName\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:565
    const redirectUri = resp.request.uri.href;

## Your Environment
 *os*:Windows_NT x64 10.0.18362
- *extension settings*:
- *nodejs version*:v14.3.0
- *vscode version*:1.45.1 
- *extension version*:

**Comment by yihong0618** [comment]
@13068240601 
有2FA的窗口，稍等下会弹出。

**Comment by 13068240601** [comment]
login: (node:13024) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: c:\Users\userName\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:565
    const redirectUri = resp.request.uri.href;
                             ^

TypeError: Cannot read property 'request' of undefined
    at Request._callback (c:\Users\userName\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:565:30)
    at self.callback (c:\Users\userName\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (c:\Users\userName\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:467:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
直接报错了，没有2fa的窗口弹出

**Comment by 13068240601** [comment]
login: (node:13024) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
pass: c:\Users\userName.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:565
const redirectUri = resp.request.uri.href;
^

TypeError: Cannot read property 'request' of undefined
at Request._callback (c:\Users\userName.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:565:30)
at self.callback (c:\Users\userName.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:185:22)
at Request.emit (events.js:315:20)
at Request.onRequestError (c:\Users\userName.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:881:8)
at ClientRequest.emit (events.js:315:20)
at TLSSocket.socketErrorListener (_http_client.js:467:9)
at TLSSocket.emit (events.js:315:20)
at emitErrorNT (internal/streams/destroy.js💯8)
at emitErrorCloseNT (internal/streams/destroy.js:68:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
直接报错了，没有2fa的窗口弹出

@yihong0618

**Comment by yihong0618** [comment]
你的验证码是邮件接收还是手机接收？
@13068240601

**Comment by 13068240601** [comment]
邮箱 @yihong0618

**Comment by yihong0618** [comment]
应该是邮箱2FA登陆的方式不同，我之后尝试一下。
我刚测试了下手机目前没问题。
关于github怎么支持国内手机号2FA，请参考这个[链接](https://gist.github.com/xcatliu/4e1d5e69fc5f8a49e4e6)
如果还不行的话你可以先用Cookie login, 这个我测验了下，应该没问题
@13068240601

**Comment by 13068240601** [comment]
好的，谢谢大佬 @yihong0618

**Comment by 13068240601** [comment]
login: (node:1284) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: twoFactorCode: c:\Users\userName\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:565
    const redirectUri = resp.request.uri.href;
                             ^

TypeError: Cannot read property 'request' of undefined
    at Request._callback (c:\Users\userName\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:565:30)
    at self.callback (c:\Users\userName\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (c:\Users\userName\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:467:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
@yihong0618 大佬，我输入了手机验证码还是报错

**Comment by yihong0618** [comment]
@13068240601 
我尝试了下，感觉新环境的问题（网络之类的），在新环境下会弹出验证码。你尝试下用[cookie](https://github.com/jdneo/vscode-leetcode/issues/478#issuecomment-564757098)能进入么？

**Comment by istanggsh** [comment]
遇到了同样的问题

**Comment by gueinhe** [comment]
同样遇到问题

**Comment by yihong0618** [comment]
@gueinhe you use leetcode or leetcode-cn?

**Comment by 13068240601** [comment]
@yihong0618 leetcode-cn

**Comment by 13068240601** [comment]
@yihong0618 cookie 验证码我都试过了，还是会报错

**Comment by yihong0618** [comment]
@All
Its the same problem as #563 
You can just update your node version.
About how to update you can also find at #563 my answers.

**Comment by jdneo** [comment]
Close as duplicated

**Comment by 13068240601** [comment]
@yihong0618 我之前node版本是14.3.0，换回lts版12.18.0还是不行

**Comment by yihong0618** [comment]
@13068240601  check your vscode working node version https://stackoverflow.com/questions/44700432/visual-studio-code-to-use-node-version-specified-by-nvm

**Comment by jdneo** [comment]
@13068240601 Or you can specify your node executable by using the setting: `leetcode.nodePath`

**Comment by jsm1003** [comment]
我也遇到了,登陆不上, 需要验证码、

**Comment by yihong0618** [comment]
> 我也遇到了,登陆不上, 需要验证码、

Please make sure your node version > 10

**Comment by rcocco** [comment]
登录leetcode英文版，输完用户名密码，邮箱能收到验证码邮件，但不给地方输入验证码，直接登录失败。
更新node到v14.15.1仍然无效。leetcode.nodePath也已经填写了这个版本的node。

(node:27444) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] You are not login yet?
(node:16012) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
login: (node:23008) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: [ERROR] Login failed. Please make sure the credential is correct.

**Comment by yihong0618** [comment]
@rcocco 试试手机的 2FA 邮箱的好像是不行的。

**Comment by Phoenix500526** [comment]
手机的 2FA 也是不行的，试图使用 cookies 来登陆，但是登陆的 cookies 很快机会消掉（登陆成功后，浏览器的 console 中的 login 请求会被刷新，然后抓不到 cookies）
