### ISSUE TITLE
[Login error] TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by yxhl** [LeetCode-OpenSource/vscode-leetcode#581]
login: (node:18296) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: c:\Users\dell\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:565
    const redirectUri = resp.request.uri.href;
                             ^

TypeError: Cannot read property 'request' of undefined
    at Request._callback (c:\Users\dell\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:565:30)
    at self.callback (c:\Users\dell\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (c:\Users\dell\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:467:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by eedsilva** [comment]
I am having the same issue.

**Comment by quanzzz123** [comment]
The same problem, have you fixed it ? Thanks in advance
