### ISSUE TITLE
LeetCode plugin failed to initialize

### ISSUE THREAD

**Issue by HyphyPan** [LeetCode-OpenSource/vscode-leetcode#594]
## 🐛 Bug Report
Leetcode failed to initialize.

## Extension Output

v6.5.0
c:\Users\Administrator\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\mkdirp\lib\opts-arg.js:7
    opts = { mode: 0o777, fs, ...opts }
                              ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\Administrator\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\mkdirp\index.js:1:79)
    at Module._compile (module.js:556:32)
c:\Users\Administrator\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\mkdirp\lib\opts-arg.js:7
    opts = { mode: 0o777, fs, ...opts }
                              ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\Administrator\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\mkdirp\index.js:1:79)
    at Module._compile (module.js:556:32)
Error: Command "node "c:\Users\Administrator\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1".

## Your Environment

- *os*: Windows 10
- *extension settings*:
- *nodejs version*:v6.5.0
- *vscode version*:1.46.1
- *extension version*:v0.17.0

**Comment by yihong0618** [comment]
@HyphyPan 
Please use rm -rf ~/.lc/ and try to login again.

**Comment by HaiyangPeng** [comment]
Since your os is windows, you should delete the whole folder of `.lc` under your user path. It works for me.
