### ISSUE TITLE
Can't load and login: command 'leetcode.signin' not found

### ISSUE THREAD

**Issue by hwm18** [LeetCode-OpenSource/vscode-leetcode#622]
## To Reproduce

Steps to reproduce the behavior.

## Extension Output

Paste here the LeetCode extension log from output channel.

v12.18.3
[WARN] Installing missing plugins, might take a while ...
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/cpp.lint.js
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/cpp.run.js
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/github.js
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/lintcode.js
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/cookie.chrome.js
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/cookie.firefox.js
[ERROR] HTTP Error: 404
[WARN] Installing missing plugins, might take a while ...
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/cpp.lint.js
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/cpp.run.js
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/github.js
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/lintcode.js
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/cookie.chrome.js
- Downloading https://raw.githubusercontent.com/leetcode-tools/leetcode-cli/master/lib/plugins/cookie.firefox.js
[ERROR] HTTP Error: 404
Error: Command ""C:\Program Files\nodejs\node.exe" "c:\Users\hwm18\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1".

## Your Environment

- *os*:  Windows_NT x64 10.0.18363
- *extension settings*:
- *nodejs version*:  v12.18.3
- *vscode version*:  1.48.2 (user setup)
- *extension version*: 0.17.0

![VS_Leetcode_Bug](https://user-images.githubusercontent.com/7017002/91368342-ad446f80-e7bd-11ea-9b20-6e5501c60984.JPG)

**Comment by Vigoose** [comment]
+1 Same issue here.

**Comment by yihong0618** [comment]
@hwm18 @Vigoose 
Please delete your .lc cache, use `rm -rf .lc`
see https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/593

**Comment by hwm18** [comment]
Cool, after delete the folder .lc, I can login success. Thank you.

**Comment by xerosanyam** [comment]
unable to login even after removing .lc

**Comment by yihong0618** [comment]
> unable to login even after removing .lc

Can you show your output?

**Comment by xerosanyam** [comment]
thanks for replying. Which output should I give? there is no leetcode tab here
![image](https://user-images.githubusercontent.com/3167278/91794228-2b7a9900-ec38-11ea-9e03-b0b59e542777.png)

**Comment by yihong0618** [comment]
@xerosanyam 
When you failed login there maybe one vscode channel popup you can click it to see the output.

**Comment by xerosanyam** [comment]
### Screen looks like this, popups are un-clickable
![image](https://user-images.githubusercontent.com/3167278/91794779-8496fc80-ec39-11ea-9bd8-701109295ed4.png)

### this is inside Log (Extension Host)
```[2020-09-01 09:34:20.939] [exthost] [info] ExtensionService#_doActivateExtension LeetCode.vscode-leetcode {"startup":false,"extensionId":{"value":"LeetCode.vscode-leetcode","_lower":"leetcode.vscode-leetcode"},"activationEvent":"onView:leetCodeExplorer"}
[2020-09-01 09:34:20.939] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/rakhi/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/out/src/extension
[2020-09-01 09:34:20.967] [exthost] [error] Activating extension LeetCode.vscode-leetcode failed due to an error:
[2020-09-01 09:34:20.968] [exthost] [error] Error: Cannot find module 'fs-extra'
Require stack:
- /Users/rakhi/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/out/src/leetCodeExecutor.js
- /Users/rakhi/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/out/src/commands/cache.js
- /Users/rakhi/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/out/src/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:764:15)
	at Module._load (internal/modules/cjs/loader.js:669:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:971:844)
	at Module.require (internal/modules/cjs/loader.js:822:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:135)
	at Object.<anonymous> (/Users/rakhi/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/out/src/leetCodeExecutor.js:13:13)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:360)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:939:10)
	at Module.load (internal/modules/cjs/loader.js:782:32)
	at Module._load (internal/modules/cjs/loader.js:695:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:971:844)
	at Module.require (internal/modules/cjs/loader.js:822:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:135)
	at Object.<anonymous> (/Users/rakhi/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/out/src/commands/cache.js:13:28)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:360)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:939:10)
	at Module.load (internal/modules/cjs/loader.js:782:32)
	at Module._load (internal/modules/cjs/loader.js:695:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:971:844)
	at Module.require (internal/modules/cjs/loader.js:822:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:135)
	at Object.<anonymous> (/Users/rakhi/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/out/src/extension.js:15:15)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:360)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:939:10)
	at Module.load (internal/modules/cjs/loader.js:782:32)
	at Module._load (internal/modules/cjs/loader.js:695:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:971:844)
	at Module.require (internal/modules/cjs/loader.js:822:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:33:604)
	at h._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:976:874)
	at h._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:875:393)
	at h._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:874:453)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:872:230)
	at h._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:612:603)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:612:281
	at Array.map (<anonymous>)
	at h._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:612:269)
	at h.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:609:745)
	at h._activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:873:122)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:882:55
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by yihong0618** [comment]
@xerosanyam 

I think you can try to reinstall vscode-leetcode the log says `fs-extra` npm model not find.

**Comment by xerosanyam** [comment]
I've tried that :(
reinstalling, reloading & installing.. but still no change

**Comment by jdneo** [comment]
@xerosanyam have you cleaned it totally before installing?

extension files stored at `$home/.vscode/extensions/xxxx`

**Comment by xerosanyam** [comment]
no, didn't delete this folder. it works now, thanks :)
