### ISSUE TITLE
I can't login in Leetcode-cn.com

### ISSUE THREAD

**Issue by shamexln** [LeetCode-OpenSource/vscode-leetcode#645]
## 🐛 Bug Report

I can't login in Leetcode-cn.com

## To Reproduce

Using Sign-in menu, enter userid and password

## Expected behavior

can login leetcode-cn.com successfully.

## Extension Output

login: (node:24316) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: - Signing in leetcode-cn.com
- Retrieving user favorites
undefined:1
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="X-UA-Compatible" content="ie=edge"><link rel="preconnect" href="https://static.leetcode-cn.com"><link rel="preconnect" href="https://assets.leetcode-cn.com"><link rel="preload" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/styles.7a1ced44.css" as="style" onload='this.onload=null,this.setAttribute("rel","stylesheet")'><link rel="preload" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-components.301b43df.css" as="style" onload='this.onload=null,this.setAttribute("rel","stylesheet")'><link rel="preload" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-modules.9786d7fa.css" as="style" onload='this.onload=null,this.setAttribute("rel","stylesheet")'><link rel="preload" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-assets.aa74dd12.css" as="style" onload='this.onload=null,this.setAttribute("rel","stylesheet")'><link rel="preload" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-main.807e1579.css" as="style" onload='this.onload=null,this.setAttribute("rel","stylesheet")'><link rel="preload" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/main.59749008.css" as="style" onload='this.onload=null,this.setAttribute("rel","stylesheet")'><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/runtime~main.c5526f0d.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/styles.7a1ced44.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-components.301b43df.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-modules.9786d7fa.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-dls.4c92b6dc.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-schema.bdc5f84a.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-track.f0491ec1.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-assets.aa74dd12.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-common.ef701afa.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-i18n.2672c2c9.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-main.807e1579.js"><link rel="preload" as="script" href="https://static.leetcode-cn.com/cn-mono-assets/production/main/main.59749008.js"><title>力扣</title><script>window.prerenderReady=!1</script><script>!function(){var e;(e=document.createElement("link").relList)&&e.supports&&e.supports("preload")||document.querySelectorAll('link[rel="preload"][as="style"]').forEach((function(e){e.onload=null,e.setAttribute("rel","stylesheet")}))}()</script></head><body><script>!function(){const t="lc-dark-side",c=localStorage.getItem(t);c&&document.body.classList.add(c)}()</script><style id="initial-loading-style">body{--initial-loading-bg:#FFF;--initial-loading-bounce-bg:#999;--loading-image:url("https://assets.leetcode-cn.com/common/light-loading.gif")}body.dark{--initial-loading-bg:#1C1C1C;--initial-loading-bounce-bg:#8A8A8A;--loading-image:url("https://assets.leetcode-cn.com/common/dark-loading.gif")}#initial-loading{position:fixed;top:0;left:0;right:0;bottom:0;display:flex;flex-direction:column;align-items:center;background:var(--initial-loading-bg);transition:opacity .6s;z-index:100}#initial-loading[data-is-hide=true]{opacity:0;pointer-events:none}#initial-loading::after,#initial-loading::before{content:" "}#initial-loading::before{flex-grow:.618}#initial-loading::after{flex-grow:1}#initial-loading .spinner{display:flex;width:50px;height:50px;background-image:var(--loading-image);background-size:contain;background-repeat:no-repeat}</style><div id="initial-loading"><div class="spinner"></div></div><div id="app"></div><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/runtime~main.c5526f0d.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/styles.7a1ced44.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-components.301b43df.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-modules.9786d7fa.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-dls.4c92b6dc.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-schema.bdc5f84a.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-track.f0491ec1.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-assets.aa74dd12.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-common.ef701afa.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-i18n.2672c2c9.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/noj-main.807e1579.js"></script><script src="https://static.leetcode-cn.com/cn-mono-assets/production/main/main.59749008.js"></script><script>if(!/prerender/i.test(navigator.userAgent)&&/leetcode-cn\.com/.test(window.location.href)){var _hmt=_hmt||[];!function(){var e=document.createElement("script");e.src="https://hm.baidu.com/hm.js?fa218a3ff7179639febdb15e372f411c";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)}(),function(){var e=document.createElement("script");e.src="https://www.googletagmanager.com/gtag/js?id=UA-131851415-1";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t),e.onload=function(){function e(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],e("js",new Date),e("config","UA-131851415-1")}}()}</script><noscript><img src="https://certify.alexametrics.com/atrk.gif?account=tIUcs1Y1Mn20Io" style="display:none" height="1" width="1" alt=""/></noscript>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (c:\Users\shamexln\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:401:28)
    at Request.self.callback (c:\Users\shamexln\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (c:\Users\shamexln\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (c:\Users\shamexln\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)

## Your Environment

- *os*:x64
- *extension settings*:default
- *nodejs version*:v.14.4.0
- *vscode version*:1.50.1
- *extension version*:v0.17.0

**Comment by mengbinhao** [comment]
same issue with me, anyone resolved?

**Comment by LesterWeng** [comment]
same issue with me

[ERROR] invalid cookie?
/Users/lester/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:569
    user.sessionId = cookieData.sessionId;
                                ^

TypeError: Cannot read property 'sessionId' of undefined

**Comment by yihong0618** [comment]
use basic way to login

**Comment by shamexln** [comment]
> use basic way to login

I already use basic way to login. But it doesn't work

**Comment by astone2014** [comment]
I have this exact same problem. Here is the output.
```
v15.0.1
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
(node:8584) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
(node:12532) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
(node:3288) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
(node:12312) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] You are not login yet?
(node:15352) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
login: (node:16976) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: - Signing in leetcode.com
[ERROR] invalid password?
```

**Comment by zhangyanrui** [comment]
1.View:show LeetCode 
2.left side.press the International icon,then change to Chinese
3. login with name and password
4. Success.

**Comment by sivanWu0222** [comment]
> 1.View:show LeetCode 2.left side.press the International icon,then change to Chinese 3. login with name and password 4. Success.

3ks，only need to change the region from international icon to china!

**Comment by chky** [comment]
> 1.View:show LeetCode 2.left side.press the International icon,then change to Chinese 3. login with name and password 4. Success.

牛了，竟然还能识别出我是中国区的账号
