### ISSUE TITLE
Error when fetch for Leetcode question 362 design hit counter

### ISSUE THREAD

**Issue by jinxuan** [LeetCode-OpenSource/vscode-leetcode#652]
## 🐛 Bug Report

When fetching this problem, crash with an exception

## To Reproduce

Search problems. 

## Extension Output

Paste here the LeetCode extension log from output channel.

```
/Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/yargs/yargs.js:1242
      else throw err
           ^

TypeError: Cannot read property 'includes' of null
    at Plugin.plugin.getProblem (/Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:31:24)
    at Plugin.plugin.getProblem (/Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/solution.discuss.js:75:15)
    at /Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/core.js:98:15
    at /Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/company.js:1527:12
    at Plugin.plugin.getProblems (/Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:16:12)
    at Plugin.plugin.getProblems (/Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/company.js:1515:15)
    at Plugin.core.getProblem (/Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/core.js:89:8)
    at Object.cmd.handler (/Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/commands/show.js:178:10)
    at Object.runCommand (/Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/Users/***/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/yargs/yargs.js:1154:41)
```

## Your Environment

- *os*: Mac OS
- *nodejs version*: 12.18.2
- *vscode version*:  1.51.1
- *extension version*: 0.17.0

**Comment by Ricccccky** [comment]
Have the same error when fetching question 1274 Number of Ships in a Rectangle.

**Comment by SR2k** [comment]
Same error when trying to fetch 276 at CN site with a paid account.

```
TypeError: Cannot read property 'includes' of null
    at Plugin.plugin.getProblem (/Users/sr2k/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:31:24)
    at Plugin.plugin.getProblem (/Users/sr2k/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/solution.discuss.js:75:15)
    at /Users/sr2k/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/core.js:98:15
    at /Users/sr2k/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/company.js:1527:12
    at Plugin.plugin.getProblems (/Users/sr2k/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:16:12)
    at Plugin.plugin.getProblems (/Users/sr2k/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/company.js:1515:15)
    at Plugin.core.getProblem (/Users/sr2k/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/core.js:89:8)
    at Object.cmd.handler (/Users/sr2k/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/commands/show.js:178:10)
    at Object.runCommand (/Users/sr2k/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/Users/sr2k/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/yargs/yargs.js:1154:41)
```
