### ISSUE TITLE
启动插件报错

### ISSUE THREAD

**Issue by Igezo7** [LeetCode-OpenSource/vscode-leetcode#666]
启动插件的时候报如下错误

v12.13.0
undefined:1
{"solution.discuss":true,"company":true,"cache":true,"retry":true,"leetcode.cn":true,"leetcode":true}}
                                                                                                     ^

SyntaxError: Unexpected token } in JSON at position 101
    at JSON.parse (<anonymous>)
    at Object.cache.get (c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\cache.js:16:15)
    at Function.Plugin.init (c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugin.js:86:23)
    at initPlugins (c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\cli.js:62:14)
    at Object.cli.run (c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\cli.js:100:3)
    at Object.<anonymous> (c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\bin\leetcode:3:23)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
undefined:1
{"solution.discuss":true,"company":true,"cache":true,"retry":true,"leetcode.cn":true,"leetcode":true}}
                                                                                                     ^

SyntaxError: Unexpected token } in JSON at position 101
    at JSON.parse (<anonymous>)
    at Object.cache.get (c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\cache.js:16:15)
    at Function.Plugin.init (c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugin.js:86:23)
    at initPlugins (c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\cli.js:62:14)
    at Object.cli.run (c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\cli.js:100:3)
    at Object.<anonymous> (c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\bin\leetcode:3:23)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
Error: Command "node "c:\Users\admin.Nuser\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1".

**Comment by yihong0618** [comment]
rm -rf  ~/.lc

**Comment by Igezo7** [comment]
> rm -rf ~/.lc

感谢，刚顺着js代码找到了，应该是缓存问题

**Comment by yihong0618** [comment]
> > rm -rf ~/.lc
> 
> 感谢，刚顺着js代码找到了，应该是缓存问题

客气。
