### ISSUE TITLE
leetcode us login failed

### ISSUE THREAD

**Issue by Immortalt** [LeetCode-OpenSource/vscode-leetcode#675]
## 🐛 Bug Report

Use Cookie Login to login the us leetcode but failed.

## To Reproduce

just do the Cookie Login
input the email, and input the Cookie value: __cfduid=d0bf1............

## Expected behavior

Cookie Login Success

## Extension Output
(node:28350) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
- Downloading problems
(node:28358) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
login: (node:28369) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
cookie: - Retrieving user favorites
[WARN] Failed to retrieve user favorites: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
- Retrieving user profile
/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/log.js:55
      let s = args.map(x => x.toString()).join(' ');
                              ^

TypeError: Cannot read property 'toString' of undefined
    at /home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/log.js:55:31
    at Array.map (<anonymous>)
    at Object.log.<computed> [as info] (/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/log.js:55:20)
    at /home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/commands/user.js:121:13
    at /home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:529:14
    at Request._callback (/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:428:19)
    at self.callback (/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.start (/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:753:10)
    at Request.write (/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:1497:10)
- Downloading problems
(node:28380) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
- Downloading problems
(node:28432) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
login: (node:28443) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
cookie: - Retrieving user favorites
[WARN] Failed to retrieve user favorites: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
- Retrieving user profile
/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/log.js:55
      let s = args.map(x => x.toString()).join(' ');
                              ^

TypeError: Cannot read property 'toString' of undefined
    at /home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/log.js:55:31
    at Array.map (<anonymous>)
    at Object.log.<computed> [as info] (/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/log.js:55:20)
    at /home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/commands/user.js:121:13
    at /home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:529:14
    at Request._callback (/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:428:19)
    at self.callback (/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.start (/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:753:10)
    at Request.write (/home/lenovo/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:1497:10)
- Downloading problems
(node:28452) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-65-generic
- *extension version*: 0.17.0

**Comment by leopku** [comment]
same issue

**Comment by Anderbone** [comment]
Same

**Comment by Coolzyh** [comment]
Same here

**Comment by santanpereira** [comment]
Same here

**Comment by rufengma** [comment]
Hi Guys,

**Comment by rufengma** [comment]
Hi Guys, I found the solution for the error message: "ToString" and failed login with your cookies.
The 1st plugin on VS Code does not work. However, we can install another 3 plugins to replace it, and I successfully logged in via Cookies. 
I attached the image here to show which three are the ones you can install.
![leetcodeVsCode](https://user-images.githubusercontent.com/24259019/123838270-d3550780-d8d9-11eb-8e7c-39654880cc2a.png)

**Comment by Anderbone** [comment]
> Hi Guys, I found the solution for the error message: "ToString" and failed login with your cookies.
> The 1st plugin on VS Code does not work. However, we can install another 3 plugins to replace it, and I successfully logged in via Cookies.
> I attached the image here to show which three are the ones you can install.
> Please make sure you have already **Uninstalled** the 1st most commented one.
> ![leetcodeVsCode](https://user-images.githubusercontent.com/24259019/123838270-d3550780-d8d9-11eb-8e7c-39654880cc2a.png)

Thank you, it works! Mainly the second one you mentioned: https://marketplace.visualstudio.com/items?itemName=Adaex.vscode-leetcode&ssr=false#overview
