### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by jingx15** [LeetCode-OpenSource/vscode-leetcode#685]
## 🐛 Bug Report

采用GitHub登录时失败
## To Reproduce

1. 选择`sign in to Leetcode`
2. 选择GitHub登录
3. 根据提示输入账号密码
4. 无弹窗等提示，查询输出后得到下文中的错误提示

## Extension Output

```
login: (node:11632) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: c:\Users\xxx\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:589
    const authenticityToken = body.match(/name="authenticity_token" value="(.*?)"/);
                                   ^

TypeError: Cannot read property 'match' of undefined
    at Request._callback (c:\Users\the-d\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:589:36)
    at self.callback (c:\Users\the-d\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\request\request.js:185:22)
    at Request.emit (node:events:378:20)
    at Request.onRequestError (c:\Users\the-d\.vscode\extensions\leetcode.vscode-leetcode-0.17.0\node_modules\request\request.js:881:8)
    at ClientRequest.emit (node:events:378:20)
    at TLSSocket.socketErrorListener (node:_http_client:462:9)
    at TLSSocket.emit (node:events:378:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

## Your Environment

- *os*: win10 20H2
- *extension settings*: 无
- *nodejs version*: v12.18.3
- *vscode version*:1.53.2
- *extension version*:0.17.0

**Comment by zhe-he** [comment]
+1

**Comment by yihong0618** [comment]
@jingx15 @zhe-he 

我解释下这块的登陆问题: 

1. leetcode-cn 目前只支持直接登陆（第三方登陆是不好用的）
2. leetcode.com 目前只支持 GitHub 登陆，我刚才测了下，至少 GitHub 没问题
3. 如果你绑定了 2FA 目前可能不支持邮箱的，我是手机没问题

**Comment by zhangyanrui** [comment]
邮箱密码无法登陆  提示invalid password

**Comment by zhangyanrui** [comment]
1.View:show LeetCode 
2.left side.press the International icon,then change to Chinese
3. login with name and password
4. Success.

**Comment by supperchong** [comment]
欢迎使用新插件 https://marketplace.visualstudio.com/items?itemName=supperchong.algorithm
### Main Features

- 代码里包含默认测试用例，也可以添加自定义的测试用例，点击测试按钮 自动在本地运行，支持链表和二叉树。

- debug 指定测试用例

- 备忘录
- 每日一题
- 支持 import module, 打包代码， 快速复制打包的代码.

- 包含周赛 (正式比赛时直接使用 submit 是无效的,应该使用复制代码，然后在浏览器提交.)
- 支持一题多解

**Comment by medmin** [comment]
> 邮箱密码无法登陆 提示invalid password

是的，总是invalid password，但我的用户名密码都没问题

**Comment by 0xfreeman** [comment]
我之前也登陆失败。刚刚我重制了密码。绑定了邮箱。用邮箱和密码登录成功了。是在leetcode-cn节点。

**Comment by chengengliu** [comment]
同样问题，刚重置了密码还是不行，美国和国内节点都试过了，请问有什么解决办法吗？

**Comment by 1ywan** [comment]
same issue while log in us-endpoint.

**Comment by TinyZzh** [comment]
Any suggesttions?
