### ISSUE TITLE
Error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by qingbol** [LeetCode-OpenSource/vscode-leetcode#741]
I tyied to login leetcode.com in Chinamainland with cookie. Unfortunately I got this error:

> v13.2.0

> 
>  Active  Name               Version         Desc
> ----------------------------------------------------------------------------------------------------
>    ✘     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
>    ✔     company            2017.12.18      Plugin to query by company for free user.
>    ✔     cache              default         Plugin to provide local cache.
>    ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
>    ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
>    ✔     leetcode           default         Plugin to talk with leetcode APIs.
>  Active  Name               Version         Desc
> ----------------------------------------------------------------------------------------------------
>    ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
>    ✔     company            2017.12.18      Plugin to query by company for free user.
>    ✔     cache              default         Plugin to provide local cache.
>    ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
>    ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
>    ✔     leetcode           default         Plugin to talk with leetcode APIs.
>  Active  Name               Version         Desc
> ----------------------------------------------------------------------------------------------------
>    ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
>    ✔     company            2017.12.18      Plugin to query by company for free user.
>    ✔     cache              default         Plugin to provide local cache.
>    ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
>    ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
>    ✔     leetcode           default         Plugin to talk with leetcode APIs.
>  Active  Name               Version         Desc
> ----------------------------------------------------------------------------------------------------
>    ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
>    ✔     company            2017.12.18      Plugin to query by company for free user.
>    ✔     cache              default         Plugin to provide local cache.
>    ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
>    ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
>    ✔     leetcode           default         Plugin to talk with leetcode APIs.
> [ERROR] You are not login yet?
> login: pass: /Users/ttt/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:577
>     const authenticityToken = body.match(/name="authenticity_token" value="(.*?)"/);
>                                    ^
> 
> TypeError: Cannot read property 'match' of undefined
>     at Request._callback (/Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:577:36)
>     at self.callback (/Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:210:5)
>     at Request.onRequestError (/Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/request/request.js:881:8)
>     at ClientRequest.emit (events.js:210:5)
>     at TLSSocket.socketErrorListener (_http_client.js:407:9)
>     at TLSSocket.emit (events.js:210:5)
>     at emitErrorNT (internal/streams/destroy.js:84:8)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> login: cookie: /Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:542
>     return cb('invalid cookie?');
>            ^
> 
> TypeError: cb is not a function
>     at parseCookie (/Users/tttt/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:542:12)
>     at Plugin.plugin.cookieLogin (/Users/tttt/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:565:22)
>     at /Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/commands/user.js:119:12
>     at /Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:336:32
>     at /Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/utile/node_modules/async/lib/async.js:154:25
>     at assembler (/Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:333:9)
>     at /Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:342:32
>     at /Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:625:5
>     at Interface.onLine (/Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/read/lib/read.js:111:5)
>     at Interface.emit (events.js:210:5)
> login: pass: /Users/ttt/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:552
>     const redirectUri = resp.request.uri.href;
>                              ^
> 
> TypeError: Cannot read property 'request' of undefined
>     at Request._callback (/Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:552:30)
>     at self.callback (/Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:210:5)
>     at Request.onRequestError (/Users/tarus/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/request/request.js:881:8)
>     at ClientRequest.emit (events.js:210:5)
>     at TLSSocket.socketErrorListener (_http_client.js:407:9)
>     at TLSSocket.emit (events.js:210:5)
>     at emitErrorNT (internal/streams/destroy.js:84:8)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> login: cookie: - Retrieving user favorites
> - Retrieving user profile
> Successfully cookie login as xxx
> - Downloading problems
> [ERROR] Error: Client network socket disconnected before secure TLS connection was establishe
> 

Any help is appreciated.

**Comment by qingbol** [comment]
I tried another several times, it works now.
