### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by DachuanZhao** [LeetCode-OpenSource/vscode-leetcode#744]
## 🐛 Bug Report
Here is the log :
```
login: cookie: /home/zhaodachuan/.vscode-server/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:542
    return cb('invalid cookie?');
           ^

TypeError: cb is not a function
    at parseCookie (/home/zhaodachuan/.vscode-server/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:542:12)
    at Plugin.plugin.cookieLogin (/home/zhaodachuan/.vscode-server/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:565:22)
    at /home/zhaodachuan/.vscode-server/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/commands/user.js:119:12
    at /home/zhaodachuan/.vscode-server/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:336:32
    at /home/zhaodachuan/.vscode-server/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/utile/node_modules/async/lib/async.js:154:25
    at assembler (/home/zhaodachuan/.vscode-server/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:333:9)
    at /home/zhaodachuan/.vscode-server/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:342:32
    at /home/zhaodachuan/.vscode-server/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:625:5
    at Interface.onLine (/home/zhaodachuan/.vscode-server/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/read/lib/read.js:111:5)
    at Interface.emit (events.js:315:20
```
## To Reproduce

login in wsl2 ubuntu20.04

## Your Environment

- *os*: wsl2 ubuntu20.04
- *extension settings*: default
- *nodejs version*: 12
- *vscode version*: 1.60.2
- *extension version*: v0.18.0

**Comment by exoticknight** [comment]
same here

**Comment by Chef5** [comment]
+1

**Comment by anirugu** [comment]
I am facing the same issue, Any workaround?

**Comment by LuMMao** [comment]
+1

**Comment by DemoJj** [comment]
rewrite $home/.vscode/extensions/labuladong.leetcode-helper-1.4.4/node_modules/vsc-leetcode-cli/lib/session.js file
`
session.getUser = function () {
  // return cache.get(h.KEYS.user);
  return {
    sessionId: 'Your LEETCODE_SESSION',
    sessionCSRF: 'Your csrftoken'
  }
};
`
