### ISSUE TITLE
leetcode-cn 登录无任何反应

### ISSUE THREAD

**Issue by BTBMan** [LeetCode-OpenSource/vscode-leetcode#774]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/LeetCode-OpenSource/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/LeetCode-OpenSource/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/LeetCode-OpenSource/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help

使用leetcode-cn终端 登录的时候填完用户名密码 没有任何反应 登录也不成功

看到vscode的输出窗口显示这么一大堆内容
```
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
(node:18888) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] You are not login yet?
(node:18898) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
login: (node:18913) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: /Users/john_long/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:612
      if (resp.statusCode !== 200) {
               ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/Users/john_long/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:612:16)
    at self.callback (/Users/john_long/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/Users/john_long/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21
```

**Comment by BTBMan** [comment]
@Karenlrx 之前用的 github 第三方登录会报错 通过 #685 得知换成帐号密码登录后成功了
