### ISSUE TITLE
can't login in leetcode

### ISSUE THREAD

**Issue by yuliyu123** [LeetCode-OpenSource/vscode-leetcode#785]
can't log in leetcode now, error msg as below:

`(node:4979) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] You are not login yet?
(node:4980) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
login: (node:4984) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: /Users/looperX/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:552
    const redirectUri = resp.request.uri.href;
                             ^

TypeError: Cannot read properties of undefined (reading 'request')
    at Request._callback (/Users/looperX/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:552:30)
    at self.callback (/Users/looperX/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/request/request.js:185:22)
    at Request.emit (node:events:520:28)
    at Request.onRequestError (/Users/looperX/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/request/request.js:881:8)
    at ClientRequest.emit (node:events:520:28)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
login: (node:5023) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: - Signing in leetcode.com
[ERROR] invalid password?`

**Comment by Rock070** [comment]
I faced this problem too, is anyone solved?

**Comment by ehaynes99** [comment]
https://github.com/LeetCode-OpenSource/vscode-leetcode#%EF%B8%8F-attention-%EF%B8%8F--workaround-to-login-to-leetcode-endpoint

It's actually the [comment above the one linked](https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/478#issuecomment-559346357) that shows the steps. The cookie won't look like the image, but just copy the entire cookie value and paste it into the `Cookie` login.
