### ISSUE TITLE
Unable to open Q1152

### ISSUE THREAD

**Issue by howieraem** [LeetCode-OpenSource/vscode-leetcode#811]
## 🐛 Bug Report

Cannot open Q1152 (requires premium subsription)

## To Reproduce

Login with a US premium account and try opening Q1152.

## Expected behavior

It should show the problem description like other premium questions. So far other premium questions have no problem.

## Extension Output

```
/home/usr/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

TypeError: Cannot read properties of null (reading 'includes')
    at Plugin.plugin.getProblem (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:46:24)
    at Plugin.plugin.getProblem (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/solution.discuss.js:75:15)
    at /home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/core.js:98:15
    at /home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/company.js:1527:12
    at Plugin.plugin.getProblems (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:30:12)
    at Plugin.plugin.getProblems (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/company.js:1515:15)
    at Plugin.core.getProblem (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/core.js:89:8)
    at Object.cmd.handler (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/commands/show.js:184:10)
    at Object.runCommand (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/yargs/build/lib/yargs.js:1043:55)
```

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- *os*: Ubuntu 20.04
- *extension settings*: 
- *nodejs version*: 16.13.2
- *vscode version*: 1.63.2
- *extension version*: 0.18.1

**Comment by howieraem** [comment]
Same bug in opening Q428

**Comment by howieraem** [comment]
A slightly different output when I tried to open Q431
```
/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/commands/show.js:105
    .map(x => h.badge(x.value, 'yellow'))
     ^

TypeError: Cannot read properties of null (reading 'map')
    at showProblem (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/commands/show.js:105:6)
    at /home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/commands/show.js:186:7
    at /home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/solution.discuss.js:76:45
    at /home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:64:12
    at _cb (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/retry.js:45:21)
    at Request._callback (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:173:12)
    at Request.self.callback (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/home/jl/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/request/request.js:1161:10)
    at Request.emit (node:events:390:28)
```

**Comment by baluoteliz** [comment]
i have the same issue, how to solve it?

**Comment by baluoteliz** [comment]
> i have the same issue, how to solve it?

It's very strange. I keep getting various errors.
At first I thought it was an email problem, but later I checked the nodejs version;
Later, just restart vscode continuously. and then its ok。

![image](https://github.com/LeetCode-OpenSource/vscode-leetcode/assets/24445523/3e591088-1ecf-4dbd-9e74-d18e7c0cb910)

so I think All other questions here。
