### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by iDestin** [LeetCode-OpenSource/vscode-leetcode#869]
## 🐛 Bug Report
when i was login in, i get this error
```
pass: - Signing in leetcode.cn
- Retrieving user favorites
[WARN] Favorite not found?
- Retrieving user profile
/Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/log.js:55
      let s = args.map(x => x.toString()).join(' ');
                              ^

TypeError: Cannot read property 'toString' of undefined
    at /Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/log.js:55:31
    at Array.map (<anonymous>)
    at Object.log.<computed> [as info] (/Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/log.js:55:20)
    at /Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/commands/user.js:73:13
    at /Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:92:12
    at /Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:523:14
    at Request._callback (/Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:422:19)
    at Request.self.callback (/Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/request/request.js:1161:10)
```

## To Reproduce

1. install v0.18.1
2. click sign to LeetCode
3. input your email and password
4. get this error

## Expected behavior

Normal login

## Extension Output

```
pass: - Signing in leetcode.cn
- Retrieving user favorites
[WARN] Favorite not found?
- Retrieving user profile
/Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/log.js:55
      let s = args.map(x => x.toString()).join(' ');
                              ^

TypeError: Cannot read property 'toString' of undefined
    at /Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/log.js:55:31
    at Array.map (<anonymous>)
    at Object.log.<computed> [as info] (/Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/log.js:55:20)
    at /Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/commands/user.js:73:13
    at /Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:92:12
    at /Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:523:14
    at Request._callback (/Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:422:19)
    at Request.self.callback (/Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/Users/qiang/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/request/request.js:1161:10)
```

## Your Environment

- *os*: MacOs 13.2
- *extension settings*: leetcode.cn
- *nodejs version*: v14.17.5
- *vscode version*: v1.76.0
- *extension version*: v0.18.1

**Comment by EluvK** [comment]
This helps me with undefined 'toString' login problem , thx.
