### ISSUE TITLE
login error forever - lajiruanjian buhuizaiyong

### ISSUE THREAD

**Issue by Zmystie** [LeetCode-OpenSource/vscode-leetcode#939]
## 🐛 Bug Report

When I try to log in with leetcode creditial - doesn't support US
log in with Github - doesn't work: [GitHub] Please verify your device
log in with cookies -  doesn't work with the following error: 
`login: cookie: - Retrieving user favorites
[WARN] Failed to retrieve user favorites: [object Object]
- Retrieving user profile
/Users/**/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/log.js:55
      let s = args.map(x => x.toString()).join(' ');
                              ^

TypeError: Cannot read property 'toString' of undefined
    at /Users/**/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/log.js:55:31
    at Array.map (<anonymous>)
    at Object.log.<computed> [as info] (/Users/**/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/log.js:55:20)
    at /Users/**/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/commands/user.js:121:13
    at /Users/**/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:523:14
    at Request._callback (/Users/**/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:422:19)
    at Request.self.callback (/Users/**/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/Users/zmy/.vscode/extensions/leetcode.vscode-leetcode-0.18.1/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)`

## To Reproduce

Steps to reproduce the behavior.

## Extension Output

As above.

## Your Environment

- *os*: mac Version 13.3.1 (22E261)
- *extension settings*: 
- *nodejs version*:
- *vscode version*:
- *extension version*: v0.18.1

**Comment by maoding1** [comment]
same question

**Comment by LiuJiLan** [comment]
same problem
